// Interface automatically generated by schemas-to-ts

export interface Class {
  monthlyPrice?: string;
  yearlyPrice?: string;
  monthlyPricePaymentLink?: string;
  yearlyPricePaymentLink?: string;
  actionButtonText?: string;
}
export interface Class_Plain {
  monthlyPrice?: string;
  yearlyPrice?: string;
  monthlyPricePaymentLink?: string;
  yearlyPricePaymentLink?: string;
  actionButtonText?: string;
}

export interface Class_NoRelations {
  monthlyPrice?: string;
  yearlyPrice?: string;
  monthlyPricePaymentLink?: string;
  yearlyPricePaymentLink?: string;
  actionButtonText?: string;
}

