// Interface automatically generated by schemas-to-ts

export interface Price {
  suggestedPrice?: string;
  actionButtonText?: string;
}
export interface Price_Plain {
  suggestedPrice?: string;
  actionButtonText?: string;
}

export interface Price_NoRelations {
  suggestedPrice?: string;
  actionButtonText?: string;
}

