// Interface automatically generated by schemas-to-ts

export interface Price {
  price?: string;
  actionButtonText?: string;
  shortActionButtonText?: string;
  contactEmail?: string;
}
export interface Price_Plain {
  price?: string;
  actionButtonText?: string;
  shortActionButtonText?: string;
  contactEmail?: string;
}

export interface Price_NoRelations {
  price?: string;
  actionButtonText?: string;
  shortActionButtonText?: string;
  contactEmail?: string;
}

