// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface AboutPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    first_block_title?: string;
    first_block_text?: string;
    second_block_title?: string;
    second_block_text?: string;
    third_block_title?: string;
    third_block_text?: string;
    main_image?: { data: Media };
    directions_title?: string;
    directions_text?: string;
  };
}
export interface AboutPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  first_block_title?: string;
  first_block_text?: string;
  second_block_title?: string;
  second_block_text?: string;
  third_block_title?: string;
  third_block_text?: string;
  main_image?: Media_Plain;
  directions_title?: string;
  directions_text?: string;
}

export interface AboutPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  first_block_title?: string;
  first_block_text?: string;
  second_block_title?: string;
  second_block_text?: string;
  third_block_title?: string;
  third_block_text?: string;
  main_image?: number;
  directions_title?: string;
  directions_text?: string;
}

export interface AboutPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  first_block_title?: string;
  first_block_text?: string;
  second_block_title?: string;
  second_block_text?: string;
  third_block_title?: string;
  third_block_text?: string;
  main_image?: AdminPanelRelationPropertyModification<Media_Plain>;
  directions_title?: string;
  directions_text?: string;
}
