// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface ArtWork {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    image: { data: Media };
    caption?: string;
    rank?: number;
  };
}
export interface ArtWork_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: Media_Plain;
  caption?: string;
  rank?: number;
}

export interface ArtWork_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: number;
  caption?: string;
  rank?: number;
}

export interface ArtWork_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: AdminPanelRelationPropertyModification<Media_Plain>;
  caption?: string;
  rank?: number;
}
