// Interface automatically generated by schemas-to-ts

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    address?: string;
    visitHours?: string;
    contactEmail?: string;
    instagramLink?: string;
    visitHoursTitle?: string;
    contactTitle?: string;
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  address?: string;
  visitHours?: string;
  contactEmail?: string;
  instagramLink?: string;
  visitHoursTitle?: string;
  contactTitle?: string;
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  address?: string;
  visitHours?: string;
  contactEmail?: string;
  instagramLink?: string;
  visitHoursTitle?: string;
  contactTitle?: string;
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  address?: string;
  visitHours?: string;
  contactEmail?: string;
  instagramLink?: string;
  visitHoursTitle?: string;
  contactTitle?: string;
}
