// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface LandingPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    offering_header?: string;
    journal_header?: string;
    artist_work_header?: string;
    journal_section_image?: { data: Media };
    locale: string;
    localizations?: { data: LandingPage[] };
  };
}
export interface LandingPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  offering_header?: string;
  journal_header?: string;
  artist_work_header?: string;
  journal_section_image?: Media_Plain;
  locale: string;
  localizations?: LandingPage_Plain[];
}

export interface LandingPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  offering_header?: string;
  journal_header?: string;
  artist_work_header?: string;
  journal_section_image?: number;
  locale: string;
  localizations?: LandingPage[];
}

export interface LandingPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  offering_header?: string;
  journal_header?: string;
  artist_work_header?: string;
  journal_section_image?: AdminPanelRelationPropertyModification<Media_Plain>;
  locale: string;
  localizations?: LandingPage[];
}
