// Interface automatically generated by schemas-to-ts

export interface LandingPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    offering_header?: string;
    journal_header?: string;
    artist_work_header?: string;
    locale: string;
    localizations?: { data: LandingPage[] };
  };
}
export interface LandingPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  offering_header?: string;
  journal_header?: string;
  artist_work_header?: string;
  locale: string;
  localizations?: LandingPage_Plain[];
}

export interface LandingPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  offering_header?: string;
  journal_header?: string;
  artist_work_header?: string;
  locale: string;
  localizations?: LandingPage[];
}

export interface LandingPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  offering_header?: string;
  journal_header?: string;
  artist_work_header?: string;
  locale: string;
  localizations?: LandingPage[];
}
