// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Instructor } from './instructor';
import { Media_Plain } from '../common/Media';
import { Instructor_Plain } from './instructor';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export enum Status {
  Active = 'active',
  Suspended = 'suspended',
  Finished = 'finished',}

export interface Offering {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: string;
    starting_date?: Date;
    slug: string;
    status?: Status;
    event_info?: string;
    square_image: { data: Media };
    ending_date?: Date;
    starting_time?: Date;
    ending_time?: Date;
    instructors?: { data: Instructor[] };
    days?: string;
    rectangle_image?: { data: Media };
  };
}
export interface Offering_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  starting_date?: Date;
  slug: string;
  status?: Status;
  event_info?: string;
  square_image: Media_Plain;
  ending_date?: Date;
  starting_time?: Date;
  ending_time?: Date;
  instructors?: Instructor_Plain[];
  days?: string;
  rectangle_image?: Media_Plain;
}

export interface Offering_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  starting_date?: Date;
  slug: string;
  status?: Status;
  event_info?: string;
  square_image: number;
  ending_date?: Date;
  starting_time?: Date;
  ending_time?: Date;
  instructors?: number[];
  days?: string;
  rectangle_image?: number;
}

export interface Offering_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  starting_date?: Date;
  slug: string;
  status?: Status;
  event_info?: string;
  square_image: AdminPanelRelationPropertyModification<Media_Plain>;
  ending_date?: Date;
  starting_time?: Date;
  ending_time?: Date;
  instructors?: AdminPanelRelationPropertyModification<Instructor_Plain>;
  days?: string;
  rectangle_image?: AdminPanelRelationPropertyModification<Media_Plain>;
}
