// Interface automatically generated by schemas-to-ts

import { Offering } from './offering';
import { Offering_Plain } from './offering';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface OfferingType {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Name?: string;
    offerings: { data: Offering[] };
  };
}
export interface OfferingType_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  offerings: Offering_Plain[];
}

export interface OfferingType_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  offerings: number[];
}

export interface OfferingType_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  offerings: AdminPanelRelationPropertyModification<Offering_Plain>;
}
