// Interface automatically generated by schemas-to-ts

export interface OfferingPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    about_offering_title?: string;
    event_info_title?: string;
    other_offerings_title?: string;
    apply_now_button_title?: string;
  };
}
export interface OfferingPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  about_offering_title?: string;
  event_info_title?: string;
  other_offerings_title?: string;
  apply_now_button_title?: string;
}

export interface OfferingPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  about_offering_title?: string;
  event_info_title?: string;
  other_offerings_title?: string;
  apply_now_button_title?: string;
}

export interface OfferingPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  about_offering_title?: string;
  event_info_title?: string;
  other_offerings_title?: string;
  apply_now_button_title?: string;
}
